"""
Portfolio Monitor Service.
Runs scheduled AI analysis on manual positions and sends notifications.
"""
from __future__ import annotations

import hashlib
import html
import json
import os
import re
import threading
import time
import traceback
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Dict, List, Optional

from app.utils.db import get_db_connection
from app.utils.logger import get_logger
from app.services.fast_analysis import get_fast_analysis_service
from app.services.signal_notifier import SignalNotifier
from app.services.kline import KlineService
from app.services.billing_service import get_billing_service
from app.services.portfolio_monitor_i18n import get_alert_message, get_alert_title
from app.services.portfolio_monitor_notifications import resolve_notification_delivery
from app.utils.json_helpers import safe_json_loads
from app.utils.resource_guard import is_fd_cooldown_active, fd_cooldown_remaining

logger = get_logger(__name__)

DEFAULT_USER_ID = 1

_monitor_thread: Optional[threading.Thread] = None
_stop_event = threading.Event()

MAX_ALERTS_PER_MONITOR_TICK = 300


def _due_monitor_batch_limit() -> int:
    try:
        return max(1, min(20, int(os.getenv("PORTFOLIO_MONITOR_DUE_BATCH_LIMIT", "5"))))
    except Exception:
        return 5



def _now_ts() -> int:
    return int(time.time())


def _language_key(language: str = "") -> str:
    lang = (language or "").replace("_", "-").lower()
    if lang.startswith("zh-tw") or lang.startswith("zh-hk") or lang.startswith("zh-hant"):
        return "zh-TW"
    if lang.startswith("zh"):
        return "zh-CN"
    for key in ("ja", "ko", "de", "fr", "ru", "ar", "th", "vi"):
        if lang.startswith(key):
            return key
    return "en"


_OUTLOOK_LABELS: Dict[str, Dict[str, str]] = {
    "en": {"BUY": "Bullish", "SELL": "Bearish", "HOLD": "Neutral"},
    "zh-CN": {"BUY": "利多", "SELL": "利空", "HOLD": "中性"},
    "zh-TW": {"BUY": "利多", "SELL": "利空", "HOLD": "中性"},
    "ja": {"BUY": "強気", "SELL": "弱気", "HOLD": "中立"},
    "ko": {"BUY": "강세", "SELL": "약세", "HOLD": "중립"},
    "de": {"BUY": "Bullisch", "SELL": "Bärisch", "HOLD": "Neutral"},
    "fr": {"BUY": "Haussier", "SELL": "Baissier", "HOLD": "Neutre"},
    "ru": {"BUY": "Бычий", "SELL": "Медвежий", "HOLD": "Нейтральный"},
    "ar": {"BUY": "إيجابي", "SELL": "سلبي", "HOLD": "محايد"},
    "th": {"BUY": "เชิงบวก", "SELL": "เชิงลบ", "HOLD": "เป็นกลาง"},
    "vi": {"BUY": "Tích cực", "SELL": "Tiêu cực", "HOLD": "Trung lập"},
}


def _outlook_labels(language: str = "") -> Dict[str, str]:
    return _OUTLOOK_LABELS.get(_language_key(language), _OUTLOOK_LABELS["en"])


def _monitor_report_texts(language: str = "") -> Dict[str, str]:
    texts = {
        "title": "Portfolio AI Analysis Report",
        "subtitle": "Generated by QuantDinger Fast AI Analysis Engine",
        "kicker": "Scheduled AI Monitor",
        "overview": "Portfolio Overview",
        "positions": "Positions",
        "total_value": "Total Value",
        "total_cost": "Total Cost",
        "total_pnl": "Total P&L",
        "watchlist": "Watchlist",
        "monitor_type": "Monitor Type",
        "latest_price": "Latest Price",
        "not_applicable": "N/A",
        "ai_recommendations": "AI Outlook",
        "buy": "Bullish",
        "sell": "Bearish",
        "hold": "Neutral",
        "position_analysis": "Position Analysis",
        "current_price": "Current",
        "entry_price": "Entry",
        "pnl": "P&L",
        "quantity": "Qty",
        "side": "Side",
        "long": "Long",
        "short": "Short",
        "ai_decision": "AI Outlook",
        "confidence": "Confidence",
        "reasoning": "Summary",
        "trader_report": "Trader Analysis",
        "risk_report": "Risk Assessment",
        "overview_report": "Market Overview",
        "click_expand": "Click to expand",
        "user_focus": "User Focus",
        "generated_at": "Generated at",
        "disclaimer": "For research reference only. Not investment advice.",
        "analysis_failed": "Analysis failed",
    }
    overrides = {
        "zh-CN": {
            "title": "AI 定时分析报告", "subtitle": "由 QuantDinger 快速 AI 分析引擎生成", "kicker": "定时 AI 监控",
            "overview": "组合概览", "positions": "标的数", "total_value": "当前市值", "total_cost": "持仓成本",
            "total_pnl": "浮动盈亏", "watchlist": "观察标的", "monitor_type": "监控类型", "latest_price": "最新价格",
            "not_applicable": "不适用", "ai_recommendations": "AI 倾向分布", "buy": "利多", "sell": "利空",
            "hold": "中性", "position_analysis": "标的分析", "current_price": "当前价", "entry_price": "成本价",
            "pnl": "盈亏", "quantity": "数量", "side": "方向", "long": "做多", "short": "做空",
            "ai_decision": "AI 倾向", "confidence": "置信度", "reasoning": "摘要", "trader_report": "交易分析",
            "risk_report": "风险评估", "overview_report": "市场概览", "click_expand": "展开查看",
            "user_focus": "用户关注点", "generated_at": "生成时间", "disclaimer": "仅供研究参考，不构成投资建议。",
            "analysis_failed": "分析失败",
        },
        "zh-TW": {
            "title": "AI 定時分析報告", "subtitle": "由 QuantDinger 快速 AI 分析引擎生成", "kicker": "定時 AI 監控",
            "overview": "組合概覽", "positions": "標的數", "total_value": "目前市值", "total_cost": "持倉成本",
            "total_pnl": "浮動盈虧", "watchlist": "觀察標的", "monitor_type": "監控類型", "latest_price": "最新價格",
            "not_applicable": "不適用", "ai_recommendations": "AI 傾向分布", "buy": "利多", "sell": "利空",
            "hold": "中性", "position_analysis": "標的分析", "current_price": "目前價格", "entry_price": "成本價",
            "pnl": "盈虧", "quantity": "數量", "side": "方向", "long": "做多", "short": "做空",
            "ai_decision": "AI 傾向", "confidence": "信心度", "reasoning": "摘要", "trader_report": "交易分析",
            "risk_report": "風險評估", "overview_report": "市場概覽", "click_expand": "展開查看",
            "user_focus": "使用者關注點", "generated_at": "生成時間", "disclaimer": "僅供研究參考，不構成投資建議。",
            "analysis_failed": "分析失敗",
        },
        "ja": {"buy": "強気", "sell": "弱気", "hold": "中立", "ai_recommendations": "AI 見通し", "ai_decision": "AI 見通し"},
        "ko": {"buy": "강세", "sell": "약세", "hold": "중립", "ai_recommendations": "AI 전망", "ai_decision": "AI 전망"},
        "de": {"buy": "Bullisch", "sell": "Bärisch", "hold": "Neutral", "ai_recommendations": "AI-Ausblick", "ai_decision": "AI-Ausblick"},
        "fr": {"buy": "Haussier", "sell": "Baissier", "hold": "Neutre", "ai_recommendations": "Perspective IA", "ai_decision": "Perspective IA"},
        "ru": {"buy": "Бычий", "sell": "Медвежий", "hold": "Нейтральный", "ai_recommendations": "Прогноз ИИ", "ai_decision": "Прогноз ИИ"},
        "ar": {"buy": "إيجابي", "sell": "سلبي", "hold": "محايد", "ai_recommendations": "توقعات الذكاء الاصطناعي", "ai_decision": "توقعات الذكاء الاصطناعي"},
        "th": {"buy": "เชิงบวก", "sell": "เชิงลบ", "hold": "เป็นกลาง", "ai_recommendations": "มุมมอง AI", "ai_decision": "มุมมอง AI"},
        "vi": {"buy": "Tích cực", "sell": "Tiêu cực", "hold": "Trung lập", "ai_recommendations": "Nhận định AI", "ai_decision": "Nhận định AI"},
    }
    texts.update(overrides.get(_language_key(language), {}))
    return texts


def _bump_monitor_schedule(
    monitor_id: int,
    interval_minutes: int,
    last_result: Any,
    skipped: bool = False,
) -> None:
    """Advance ``next_run_at`` after a monitor cycle (real run or skip).

    Both INSERT (creation) and UPDATE paths must produce timestamps with the
    same time-zone semantics; ``qd_position_monitors`` columns are naive
    ``TIMESTAMP``, so we let PostgreSQL compute everything via ``NOW()`` and
    ``INTERVAL`` to stay consistent with the creation path in
    ``routes/portfolio.py``.

    When ``skipped`` is True we keep ``last_run_at`` and ``run_count`` as-is
    (since the monitor didn't actually consume an analysis cycle), but we
    still push ``next_run_at`` forward so the loop does not keep firing the
    same monitor every 30 seconds while the underlying condition (no credits,
    symbol removed from watchlist, etc.) persists.
    """
    try:
        interval = int(interval_minutes or 60)
        if interval <= 0:
            interval = 60
        # Cap at one week to avoid pathological intervals from bad configs.
        interval = min(interval, 60 * 24 * 7)

        result_json = json.dumps(last_result, ensure_ascii=False, default=str)

        with get_db_connection() as db:
            cur = db.cursor()
            if skipped:
                cur.execute(
                    """
                    UPDATE qd_position_monitors
                    SET next_run_at = NOW() + INTERVAL '%s minutes',
                        last_result = ?,
                        updated_at = NOW()
                    WHERE id = ?
                    """,
                    (interval, result_json, monitor_id),
                )
            else:
                cur.execute(
                    """
                    UPDATE qd_position_monitors
                    SET last_run_at = NOW(),
                        next_run_at = NOW() + INTERVAL '%s minutes',
                        last_result = ?,
                        run_count = run_count + 1,
                        updated_at = NOW()
                    WHERE id = ?
                    """,
                    (interval, result_json, monitor_id),
                )
            db.commit()
            cur.close()
    except Exception as e:
        logger.error(f"_bump_monitor_schedule failed for monitor #{monitor_id}: {e}")


def _get_positions_for_monitor(position_ids: List[int] = None, user_id: int = None) -> List[Dict[str, Any]]:
    """Get positions, optionally filtered by IDs and user_id."""
    try:
        kline_service = KlineService()
        effective_user_id = user_id if user_id is not None else DEFAULT_USER_ID
        
        with get_db_connection() as db:
            cur = db.cursor()
            if position_ids:
                placeholders = ','.join(['?' for _ in position_ids])
                cur.execute(
                    f"""
                    SELECT id, market, symbol, name, side, quantity, entry_price, group_name
                    FROM qd_manual_positions
                    WHERE user_id = ? AND id IN ({placeholders})
                    """,
                    [effective_user_id] + list(position_ids)
                )
            else:
                cur.execute(
                    """
                    SELECT id, market, symbol, name, side, quantity, entry_price, group_name
                    FROM qd_manual_positions
                    WHERE user_id = ?
                    """,
                    (effective_user_id,)
                )
            rows = cur.fetchall() or []
            cur.close()

        positions = []
        for row in rows:
            market = row.get('market')
            symbol = row.get('symbol')
            entry_price = float(row.get('entry_price') or 0)
            quantity = float(row.get('quantity') or 0)
            side = row.get('side') or 'long'
            group_name = row.get('group_name')
            
            # Get current price (use realtime price API)
            current_price = 0
            try:
                price_data = kline_service.get_realtime_price(market, symbol)
                current_price = float(price_data.get('price') or 0)
            except Exception:
                pass
            
            # Calculate PnL
            if side == 'long':
                pnl = (current_price - entry_price) * quantity
            else:
                pnl = (entry_price - current_price) * quantity
            
            pnl_percent = round(pnl / (entry_price * quantity) * 100, 2) if entry_price * quantity > 0 else 0
            
            positions.append({
                'id': row.get('id'),
                'market': market,
                'symbol': symbol,
                'name': row.get('name') or symbol,
                'side': side,
                'quantity': quantity,
                'entry_price': entry_price,
                'current_price': current_price,
                'pnl': round(pnl, 2),
                'pnl_percent': pnl_percent,
                'group_name': group_name
            })
        
        return positions
    except Exception as e:
        logger.error(f"_get_positions_for_monitor failed: {e}")
        return []


MAX_PARALLEL_ANALYSIS = 5


def _analyze_single_position(pos: Dict[str, Any], language: str, user_id: int = None) -> Dict[str, Any]:
    """Analyze a single position (designed to run inside a thread pool)."""
    market = pos.get('market')
    symbol = pos.get('symbol')
    name = pos.get('name') or symbol
    group_name = pos.get('group_name')

    if not market or not symbol:
        return {'market': market, 'symbol': symbol, 'name': name, 'error': 'missing market/symbol'}

    try:
        logger.info(f"Running fast AI analysis for {market}:{symbol} (user={user_id})")
        service = get_fast_analysis_service()
        analysis_result = service.analyze(
            market=market, symbol=symbol, language=language, timeframe='1D',
            user_id=user_id,
        )

        detailed = analysis_result.get('detailed_analysis', {})
        trading_plan = analysis_result.get('trading_plan', {})
        scores = analysis_result.get('scores', {})
        risks = analysis_result.get('risks', [])
        risk_report = '\n'.join([f"- {r}" for r in risks]) if risks else ''

        result = {
            'market': market, 'symbol': symbol, 'name': name, 'group_name': group_name,
            'entry_price': pos.get('entry_price'),
            'current_price': pos.get('current_price') or analysis_result.get('market_data', {}).get('current_price'),
            'pnl': pos.get('pnl'), 'pnl_percent': pos.get('pnl_percent'),
            'quantity': pos.get('quantity'), 'side': pos.get('side'),
            'final_decision': analysis_result.get('decision', 'HOLD'),
            'confidence': analysis_result.get('confidence', 50),
            'reasoning': analysis_result.get('summary', ''),
            'trader_decision': analysis_result.get('decision', 'HOLD'),
            'trader_reasoning': analysis_result.get('summary', ''),
            'overview_report': detailed.get('technical', ''),
            'fundamental_report': detailed.get('fundamental', ''),
            'sentiment_report': detailed.get('sentiment', ''),
            'risk_report': risk_report,
            'suggested_entry': trading_plan.get('entry_price'),
            'suggested_stop_loss': trading_plan.get('stop_loss'),
            'suggested_take_profit': trading_plan.get('take_profit'),
            'technical_score': scores.get('technical', 50),
            'fundamental_score': scores.get('fundamental', 50),
            'sentiment_score': scores.get('sentiment', 50),
            'key_reasons': analysis_result.get('reasons', []),
            'error': analysis_result.get('error')
        }
        logger.info(f"Fast analysis completed for {market}:{symbol}: {analysis_result.get('decision', 'N/A')}")
        return result
    except Exception as e:
        logger.error(f"Failed to analyze {market}:{symbol}: {e}")
        return {'market': market, 'symbol': symbol, 'name': name, 'error': str(e)}


def _run_ai_analysis(positions: List[Dict[str, Any]], config: Dict[str, Any], user_id: int = None) -> Dict[str, Any]:
    """
    Run fast AI analysis on positions **in parallel** using a thread pool.
    Same (market, symbol) is analyzed only once; the result is shared across
    duplicate positions so we don't waste LLM calls or show redundant entries.
    """
    try:
        language = config.get('language', 'en-US')
        custom_prompt = config.get('prompt', '')

        # Deduplicate by (market, symbol) to avoid repeated LLM calls.
        unique_map: Dict[str, int] = {}          # "market|symbol" -> index in unique_positions
        unique_positions: List[Dict[str, Any]] = []
        pos_to_unique: List[int] = []             # positions[i] -> unique_positions index
        for pos in positions:
            key = f"{pos.get('market')}|{pos.get('symbol')}"
            if key not in unique_map:
                unique_map[key] = len(unique_positions)
                unique_positions.append(pos)
            pos_to_unique.append(unique_map[key])

        workers = min(len(unique_positions), MAX_PARALLEL_ANALYSIS)
        unique_analyses: List[Dict[str, Any]] = [None] * len(unique_positions)

        with ThreadPoolExecutor(max_workers=workers) as executor:
            future_to_idx = {
                executor.submit(_analyze_single_position, pos, language, user_id): idx
                for idx, pos in enumerate(unique_positions)
            }
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                try:
                    unique_analyses[idx] = future.result()
                except Exception as e:
                    pos = unique_positions[idx]
                    unique_analyses[idx] = {
                        'market': pos.get('market'), 'symbol': pos.get('symbol'),
                        'name': pos.get('name') or pos.get('symbol'), 'error': str(e)
                    }

        # Map back: each position gets its own copy with position-specific P&L.
        position_analyses: List[Dict[str, Any]] = []
        seen_keys: set = set()
        for i, pos in enumerate(positions):
            key = f"{pos.get('market')}|{pos.get('symbol')}"
            if key in seen_keys:
                continue
            seen_keys.add(key)
            base = dict(unique_analyses[pos_to_unique[i]])
            base['entry_price'] = pos.get('entry_price')
            base['current_price'] = base.get('current_price') or pos.get('current_price')
            combined_qty = sum(
                float(p.get('quantity') or 0)
                for j, p in enumerate(positions)
                if f"{p.get('market')}|{p.get('symbol')}" == key
            )
            combined_cost = sum(
                float(p.get('entry_price') or 0) * float(p.get('quantity') or 0)
                for j, p in enumerate(positions)
                if f"{p.get('market')}|{p.get('symbol')}" == key
            )
            cur_price = float(base.get('current_price') or 0)
            combined_pnl = sum(
                float(p.get('pnl') or 0)
                for j, p in enumerate(positions)
                if f"{p.get('market')}|{p.get('symbol')}" == key
            )
            avg_entry = round(combined_cost / combined_qty, 4) if combined_qty else 0
            pnl_pct = round(combined_pnl / combined_cost * 100, 2) if combined_cost else 0
            base['quantity'] = combined_qty
            base['entry_price'] = avg_entry
            base['pnl'] = round(combined_pnl, 2)
            base['pnl_percent'] = pnl_pct
            position_analyses.append(base)

        # Also provide deduplicated positions list for report building
        deduped_positions = []
        seen_keys2: set = set()
        for i, pos in enumerate(positions):
            key = f"{pos.get('market')}|{pos.get('symbol')}"
            if key in seen_keys2:
                continue
            seen_keys2.add(key)
            merged = dict(pos)
            merged['quantity'] = position_analyses[len(deduped_positions)].get('quantity', pos.get('quantity'))
            merged['entry_price'] = position_analyses[len(deduped_positions)].get('entry_price', pos.get('entry_price'))
            merged['pnl'] = position_analyses[len(deduped_positions)].get('pnl', pos.get('pnl'))
            merged['pnl_percent'] = position_analyses[len(deduped_positions)].get('pnl_percent', pos.get('pnl_percent'))
            deduped_positions.append(merged)

        analysis_report = _build_comprehensive_report(deduped_positions, position_analyses, language, custom_prompt)

        return {
            'success': True,
            'analysis': analysis_report,
            'position_analyses': position_analyses,
            'positions': deduped_positions,
            'position_count': len(deduped_positions),
            'analyzed_count': len([p for p in position_analyses if not p.get('error')]),
            'timestamp': _now_ts()
        }

    except Exception as e:
        logger.error(f"_run_ai_analysis failed: {e}")
        logger.error(traceback.format_exc())
        return {'success': False, 'error': str(e), 'timestamp': _now_ts()}


def _build_comprehensive_report(
    positions: List[Dict[str, Any]],
    position_analyses: List[Dict[str, Any]],
    language: str,
    custom_prompt: str = ''
) -> str:
    """Build a comprehensive text report (backward compatible)."""
    # Use HTML report as the main format
    return _build_html_report(positions, position_analyses, language, custom_prompt)


_REPORT_SENTENCE_SPLIT = re.compile(
    r'(?<=[。！？!?；;])\s*|(?<=[.!?])\s+(?=[A-Z0-9])'
)
_REPORT_LIST_ITEM = re.compile(r'^\s*(?:[-*•]|\d+[.)、])\s*(.+?)\s*$')
_REPORT_EVIDENCE_ID = re.compile(r'(?<![A-Za-z0-9])ev_[A-Za-z0-9]+')
_REPORT_TECHNICAL_INCONSISTENCY_ZH = re.compile(
    r'(技术面(?:内部)?不一致|技术指标(?:内部)?不一致)'
)
_REPORT_TECHNICAL_INCONSISTENCY_EN = re.compile(
    r'(?:technical(?:\s+analysis)?\s+(?:is\s+)?internally\s+inconsistent'
    r'|technical\s+indicators?\s+(?:are\s+)?internally\s+inconsistent)',
    re.IGNORECASE,
)


def _clean_report_copy(text: Any) -> str:
    """Hide audit-only evidence IDs from legacy and newly generated reports."""
    cleaned = _REPORT_TECHNICAL_INCONSISTENCY_ZH.sub('技术面信号混合', str(text or ''))
    cleaned = _REPORT_TECHNICAL_INCONSISTENCY_EN.sub('mixed technical picture', cleaned)
    cleaned = _REPORT_EVIDENCE_ID.sub('', cleaned)
    cleaned = re.sub(r'\(\s*[、,，;；:：\s]*\)', '', cleaned)
    cleaned = re.sub(r'[\s、,，;；:：]+([)）])', r'\1', cleaned)
    cleaned = re.sub(r'[\s、,，;；:：]+([。.!?！？])', r'\1', cleaned)
    cleaned = re.sub(r'[ \t]{2,}', ' ', cleaned)
    return re.sub(r'\s+([,，。；;.!?])', r'\1', cleaned).strip()


def _join_report_sentences(first: str, second: str) -> str:
    if first and second and first[-1] in '.!?' and second[0].isascii() and second[0].isalnum():
        return f"{first} {second}"
    return f"{first}{second}"


def _format_report_prose(text: Any) -> str:
    """Render plain report text as readable paragraphs without changing its meaning."""
    raw = _clean_report_copy(text).replace('\r\n', '\n').replace('\r', '\n').strip()
    if not raw:
        return ''

    source_paragraphs = [part.strip() for part in re.split(r'\n\s*\n', raw) if part.strip()]
    output: List[str] = []
    for source in source_paragraphs:
        source = re.sub(r'\s*\n\s*', ' ', source)
        source = re.sub(r'[ \t]+', ' ', source).strip()
        if not source:
            continue

        sentences = [part.strip() for part in _REPORT_SENTENCE_SPLIT.split(source) if part.strip()]
        if len(sentences) <= 1:
            output.append(f'<p>{html.escape(source)}</p>')
            continue

        grouped: List[str] = []
        grouped_sentence_counts: List[int] = []
        for sentence in sentences:
            if (
                grouped
                and grouped_sentence_counts[-1] < 2
                and len(grouped[-1]) + len(sentence) <= 180
            ):
                grouped[-1] = _join_report_sentences(grouped[-1], sentence)
                grouped_sentence_counts[-1] += 1
            else:
                grouped.append(sentence)
                grouped_sentence_counts.append(1)
        output.extend(f'<p>{html.escape(paragraph)}</p>' for paragraph in grouped)

    return ''.join(output)


def _format_report_list(text: Any) -> str:
    """Render bullet/numbered report text as a list, falling back to prose."""
    raw = _clean_report_copy(text).replace('\r\n', '\n').replace('\r', '\n').strip()
    if not raw:
        return ''

    items: List[str] = []
    for line in raw.split('\n'):
        line = line.strip()
        if not line:
            continue
        match = _REPORT_LIST_ITEM.match(line)
        if not match:
            return _format_report_prose(raw)
        items.append(match.group(1))

    if not items:
        return ''
    return '<div class="qd-copy-list" role="list">' + ''.join(
        f'<div class="qd-copy-list-item" role="listitem">- {html.escape(item)}</div>'
        for item in items
    ) + '</div>'


def _build_html_report(
    positions: List[Dict[str, Any]],
    position_analyses: List[Dict[str, Any]],
    language: str,
    custom_prompt: str = ''
) -> str:
    """Build a beautiful HTML report with collapsible sections."""
    
    def has_holding(item: Dict[str, Any]) -> bool:
        return float(item.get('quantity') or 0) > 0 and float(item.get('entry_price') or 0) > 0

    held_positions = [p for p in positions if has_holding(p)]
    valid_analyses = [p for p in position_analyses if not p.get('error')]
    held_analyses = [p for p in valid_analyses if has_holding(p)]
    watched_analyses = [p for p in valid_analyses if not has_holding(p)]
    is_watch_only = len(held_analyses) == 0 and len(watched_analyses) > 0

    # Calculate portfolio summary. Watch-only monitors do not have cost basis.
    total_cost = sum(float(p.get('entry_price', 0)) * float(p.get('quantity', 0)) for p in held_positions)
    total_pnl = sum(float(p.get('pnl', 0)) for p in held_positions)
    total_pnl_percent = round(total_pnl / total_cost * 100, 2) if total_cost > 0 else 0
    total_market_value = sum(float(p.get('current_price', 0)) * float(p.get('quantity', 0)) for p in held_positions)
    primary_watch = watched_analyses[0] if watched_analyses else {}
    primary_price = float(primary_watch.get('current_price') or 0)
    primary_decision = str(primary_watch.get('final_decision') or 'HOLD').upper()
    primary_confidence = primary_watch.get('confidence', 0)
    
    # Count recommendations
    buy_count = len([p for p in position_analyses if p.get('final_decision') == 'BUY'])
    sell_count = len([p for p in position_analyses if p.get('final_decision') == 'SELL'])
    hold_count = len([p for p in position_analyses if p.get('final_decision') == 'HOLD'])
    
    # Text labels for the HTML report.
    texts = _monitor_report_texts(language)

    # CSS Styles
    css = '''
    <style>
        .qd-report { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; max-width: 860px; margin: 0 auto; padding: 16px; background: #ffffff; color: #111827; border: 1px solid #e7ebf3; border-radius: 8px; }
        .qd-report * { box-sizing: border-box; }
        .qd-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 18px; padding: 18px 20px; border: 1px solid #e7ebf3; border-radius: 8px; background: linear-gradient(135deg, #ffffff 0%, #f6f8fb 100%); }
        .qd-header-main { min-width: 0; }
        .qd-kicker { color: #ef4444; font-size: 12px; font-weight: 800; letter-spacing: 0; text-transform: uppercase; }
        .qd-header h1 { margin: 6px 0 8px; color: #111827; font-size: 22px; font-weight: 800; line-height: 1.25; }
        .qd-header .subtitle { color: #64748b; font-size: 13px; line-height: 1.5; }
        .qd-header-panel { flex: 0 0 auto; min-width: 172px; padding: 12px 14px; border: 1px solid #e7ebf3; border-radius: 8px; background: #ffffff; text-align: right; }
        .qd-header-panel .label { color: #64748b; font-size: 12px; }
        .qd-header-panel .value { display: block; margin-top: 4px; color: #111827; font-size: 18px; font-weight: 800; }
        .qd-header-panel .value.positive { color: #22c55e; }
        .qd-header-panel .value.negative { color: #ef4444; }
        .qd-content { display: grid; gap: 12px; margin-top: 12px; }
        .qd-section { padding: 16px; border: 1px solid #e7ebf3; border-radius: 8px; background: #f8fafc; }
        .qd-section:last-child { margin-bottom: 0; }
        .qd-section-title { display: flex; align-items: center; gap: 8px; margin: 0 0 14px; padding-bottom: 10px; border-bottom: 1px solid #e7ebf3; color: #111827; font-size: 15px; font-weight: 800; line-height: 1.3; }
        .qd-section-title:before { content: ""; width: 3px; height: 14px; border-radius: 2px; background: #ef4444; }
        .qd-overview-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 10px; }
        .qd-stat-card { min-height: 78px; padding: 12px; border: 1px solid #e7ebf3; border-radius: 8px; background: #ffffff; }
        .qd-stat-card .label { color: #64748b; font-size: 12px; margin-bottom: 8px; }
        .qd-stat-card .value { color: #111827; font-size: 19px; font-weight: 800; line-height: 1.2; word-break: break-word; }
        .qd-stat-card .value.positive { color: #22c55e; }
        .qd-stat-card .value.negative { color: #ef4444; }
        .qd-stat-card .percent { display: block; margin-top: 3px; font-size: 12px; font-weight: 700; }
        .qd-rec-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; }
        .qd-rec-card { position: relative; min-height: 100px; padding: 14px; border: 1px solid #e7ebf3; border-radius: 8px; background: #ffffff; overflow: hidden; }
        .qd-rec-card:before { content: ""; position: absolute; inset: 0 0 auto; height: 3px; background: #64748b; }
        .qd-rec-card.buy:before { background: #22c55e; }
        .qd-rec-card.sell:before { background: #ef4444; }
        .qd-rec-card.hold:before { background: #eab308; }
        .qd-rec-card.buy { background: linear-gradient(180deg, rgba(34,197,94,0.13), #ffffff 74%); }
        .qd-rec-card.sell { background: linear-gradient(180deg, rgba(239,68,68,0.13), #ffffff 74%); }
        .qd-rec-card.hold { background: linear-gradient(180deg, rgba(234,179,8,0.16), #ffffff 74%); }
        .qd-rec-card .emoji { color: #334155; font-size: 13px; font-weight: 800; letter-spacing: 0; text-transform: uppercase; }
        .qd-rec-card .count { margin-top: 10px; color: #111827; font-size: 28px; font-weight: 800; line-height: 1; }
        .qd-rec-card.buy .count { color: #22c55e; }
        .qd-rec-card.sell .count { color: #ef4444; }
        .qd-rec-card.hold .count { color: #eab308; }
        .qd-rec-card .label { margin-top: 8px; color: #64748b; font-size: 12px; }
        .qd-position { margin-bottom: 12px; overflow: hidden; border: 1px solid #e7ebf3; border-radius: 8px; background: #ffffff; }
        .qd-position:last-child { margin-bottom: 0; }
        .qd-pos-header { display: flex; justify-content: space-between; align-items: center; gap: 12px; padding: 14px 16px; background: #f8fafc; cursor: default; }
        .qd-pos-symbol { display: flex; align-items: center; gap: 12px; }
        .qd-pos-symbol .icon { flex: 0 0 auto; width: 38px; height: 38px; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 14px; color: #fff; }
        .qd-pos-symbol .icon.buy { background: #16a34a; }
        .qd-pos-symbol .icon.sell { background: #dc2626; }
        .qd-pos-symbol .icon.hold { background: #d97706; }
        .qd-pos-symbol .name { color: #111827; font-weight: 800; font-size: 15px; line-height: 1.3; }
        .qd-pos-symbol .market { margin-top: 3px; color: #64748b; font-size: 12px; }
        .qd-pos-decision { text-align: right; }
        .qd-pos-decision .decision-tag { display: inline-block; min-width: 64px; padding: 5px 10px; border-radius: 6px; font-weight: 800; font-size: 12px; text-align: center; }
        .qd-pos-decision .decision-tag.buy { background: rgba(34,197,94,0.14); color: #22c55e; border: 1px solid rgba(34,197,94,0.28); }
        .qd-pos-decision .decision-tag.sell { background: rgba(239,68,68,0.14); color: #f87171; border: 1px solid rgba(239,68,68,0.3); }
        .qd-pos-decision .decision-tag.hold { background: rgba(234,179,8,0.14); color: #facc15; border: 1px solid rgba(234,179,8,0.3); }
        .qd-pos-decision .confidence { margin-top: 5px; color: #64748b; font-size: 12px; }
        .qd-pos-stats { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 1px; background: #dbe2ec; }
        .qd-pos-stats .stat { min-width: 0; background: #ffffff; padding: 11px 12px; }
        .qd-pos-stats .stat .label { color: #64748b; font-size: 11px; margin-bottom: 5px; }
        .qd-pos-stats .stat .value { color: #111827; font-size: 13px; font-weight: 800; line-height: 1.35; word-break: break-word; }
        .qd-pos-stats .stat .value.positive { color: #22c55e; }
        .qd-pos-stats .stat .value.negative { color: #ef4444; }
        .qd-pos-reasoning { padding: 14px 16px; background: #f8fafc; border-top: 1px solid #e7ebf3; }
        .qd-pos-reasoning .label { color: #111827; font-size: 12px; font-weight: 800; margin-bottom: 6px; }
        .qd-pos-reasoning .text { color: #334155; font-size: 13px; line-height: 1.7; }
        .qd-copy p { margin: 0 0 10px; text-indent: 2em; }
        .qd-copy p:last-child { margin-bottom: 0; }
        .qd-copy-list { margin: 0; padding-left: 0; }
        .qd-copy-list-item { margin: 0 0 8px; }
        .qd-copy-list-item:last-child { margin-bottom: 0; }
        .qd-collapsible { border-top: 1px solid #e7ebf3; }
        .qd-collapsible input[type="checkbox"] { display: none; }
        .qd-collapsible-header { display: flex; justify-content: space-between; align-items: center; padding: 11px 16px; background: #f1f5f9; cursor: pointer; user-select: none; }
        .qd-collapsible-header:hover { background: #f8fafc; }
        .qd-collapsible-header .title { color: #111827; font-size: 13px; font-weight: 800; }
        .qd-collapsible-header .arrow { transition: transform 0.2s; color: #64748b; display: inline-block; }
        .qd-collapsible-content { display: none; padding: 14px 16px; background: #ffffff; color: #334155; font-size: 13px; line-height: 1.7; border-top: 1px solid #e7ebf3; }
        .qd-collapsible input[type="checkbox"]:checked ~ .qd-collapsible-content { display: block; }
        .qd-collapsible input[type="checkbox"]:checked + .qd-collapsible-header .arrow { transform: rotate(180deg); }
        .qd-user-focus { padding: 14px; border: 1px solid rgba(239,68,68,0.24); border-radius: 8px; background: rgba(239,68,68,0.07); color: #991b1b; font-size: 13px; line-height: 1.7; }
        .qd-footer { margin-top: 12px; padding: 14px 4px 2px; border-top: 1px solid #e7ebf3; text-align: center; color: #64748b; font-size: 12px; }
        .qd-footer .time { margin-bottom: 4px; }
        .qd-footer .disclaimer { opacity: 0.8; }
        .qd-error { margin: 14px 16px; border: 1px solid rgba(239,68,68,0.3); border-radius: 8px; padding: 12px; background: rgba(239,68,68,0.08); color: #b91c1c; font-size: 13px; }
        @media (max-width: 600px) {
            .qd-report { padding: 10px; border-radius: 0; }
            .qd-header { display: block; padding: 16px; }
            .qd-header-panel { margin-top: 12px; text-align: left; }
            .qd-overview-grid { grid-template-columns: repeat(2, 1fr); }
            .qd-rec-grid { grid-template-columns: repeat(3, 1fr); }
            .qd-pos-stats { grid-template-columns: repeat(2, 1fr); }
            .qd-pos-header { align-items: flex-start; }
        }
    </style>
    '''
    
    # Build HTML
    pnl_class = 'positive' if total_pnl >= 0 else 'negative'
    pnl_sign = '+' if total_pnl >= 0 else ''
    if is_watch_only:
        header_label = texts['latest_price']
        header_value = f"${primary_price:,.4f}"
        header_class = ''
        header_sub = f"{texts['ai_decision']}: {texts.get(primary_decision.lower(), primary_decision)}"
    else:
        header_label = texts['total_pnl']
        header_value = f"{pnl_sign}${total_pnl:,.2f}"
        header_class = pnl_class
        header_sub = f"({pnl_sign}{total_pnl_percent:.1f}%)"
    
    html = f'''
    {css}
    <div class="qd-report">
        <div class="qd-header">
            <div class="qd-header-main">
                <div class="qd-kicker">{texts['kicker']}</div>
                <h1>{texts['title']}</h1>
                <div class="subtitle">{texts['subtitle']}</div>
            </div>
            <div class="qd-header-panel">
                <div class="label">{header_label}</div>
                <span class="value {header_class}">{header_value}</span>
                <div class="label">{header_sub}</div>
            </div>
        </div>
        <div class="qd-content">
            <!-- Overview Section -->
            <div class="qd-section">
                <h2 class="qd-section-title">{texts['overview']}</h2>
                <div class="qd-overview-grid">
    '''

    if is_watch_only:
        html += f'''
                    <div class="qd-stat-card">
                        <div class="label">{texts['watchlist']}</div>
                        <div class="value">{len(watched_analyses)}</div>
                    </div>
                    <div class="qd-stat-card">
                        <div class="label">{texts['latest_price']}</div>
                        <div class="value">${primary_price:,.4f}</div>
                    </div>
                    <div class="qd-stat-card">
                        <div class="label">{texts['ai_decision']}</div>
                        <div class="value">{texts.get(primary_decision.lower(), primary_decision)}</div>
                    </div>
                    <div class="qd-stat-card">
                        <div class="label">{texts['confidence']}</div>
                        <div class="value">{primary_confidence}%</div>
                    </div>
        '''
    else:
        html += f'''
                    <div class="qd-stat-card">
                        <div class="label">{texts['positions']}</div>
                        <div class="value">{len(held_positions)}</div>
                    </div>
                    <div class="qd-stat-card">
                        <div class="label">{texts['total_value']}</div>
                        <div class="value">${total_market_value:,.2f}</div>
                    </div>
                    <div class="qd-stat-card">
                        <div class="label">{texts['total_cost']}</div>
                        <div class="value">${total_cost:,.2f}</div>
                    </div>
                    <div class="qd-stat-card">
                        <div class="label">{texts['total_pnl']}</div>
                        <div class="value {pnl_class}">{pnl_sign}${total_pnl:,.2f}<span class="percent">({pnl_sign}{total_pnl_percent:.1f}%)</span></div>
                    </div>
        '''

    html += f'''
                </div>
            </div>
            
            <!-- AI Outlook Section -->
            <div class="qd-section">
                <h2 class="qd-section-title">{texts['ai_recommendations']}</h2>
                <div class="qd-rec-grid">
                    <div class="qd-rec-card buy">
                        <div class="emoji">{texts['buy']}</div>
                        <div class="count">{buy_count}</div>
                        <div class="label">{texts['buy']}</div>
                    </div>
                    <div class="qd-rec-card sell">
                        <div class="emoji">{texts['sell']}</div>
                        <div class="count">{sell_count}</div>
                        <div class="label">{texts['sell']}</div>
                    </div>
                    <div class="qd-rec-card hold">
                        <div class="emoji">{texts['hold']}</div>
                        <div class="count">{hold_count}</div>
                        <div class="label">{texts['hold']}</div>
                    </div>
                </div>
            </div>
            
            <!-- Position Analysis Section -->
            <div class="qd-section">
                <h2 class="qd-section-title">{texts['position_analysis']}</h2>
    '''
    
    for pa in position_analyses:
        symbol = pa.get('symbol', '')
        name = pa.get('name', symbol)
        market = pa.get('market', '')
        group_name = pa.get('group_name', '')
        
        if pa.get('error'):
            html += f'''
                <div class="qd-position">
                    <div class="qd-pos-header">
                        <div class="qd-pos-symbol">
                            <div class="icon hold">!</div>
                            <div>
                                <div class="name">{name}</div>
                                <div class="market">{market}/{symbol}</div>
                            </div>
                        </div>
                    </div>
                    <div class="qd-error">{texts['analysis_failed']}: {pa.get('error')}</div>
                </div>
            '''
            continue
        
        decision = pa.get('final_decision', 'HOLD')
        decision_lower = decision.lower()
        decision_text = texts.get(decision_lower, decision)
        confidence = pa.get('confidence', 50)
        
        current_price = pa.get('current_price', 0)
        entry_price = pa.get('entry_price', 0)
        pnl = pa.get('pnl', 0)
        pnl_pct = pa.get('pnl_percent', 0)
        quantity = pa.get('quantity', 0)
        side = pa.get('side', 'long')
        side_text = texts['long'] if side == 'long' else texts['short']
        has_position = float(quantity or 0) > 0 and float(entry_price or 0) > 0
        
        pnl_class = 'positive' if pnl >= 0 else 'negative'
        pnl_sign = '+' if pnl >= 0 else ''
        
        reasoning = pa.get('reasoning', '')
        trader_reasoning = pa.get('trader_reasoning', '')
        overview_report = pa.get('overview_report', '')
        risk_report = pa.get('risk_report', '')
        
        html += f'''
                <div class="qd-position">
                    <div class="qd-pos-header">
                        <div class="qd-pos-symbol">
                            <div class="icon {decision_lower}">{decision[0]}</div>
                            <div>
                                <div class="name">{name}</div>
                                <div class="market">{market}/{symbol}</div>
                            </div>
                        </div>
                        <div class="qd-pos-decision">
                            <div class="decision-tag {decision_lower}">{decision_text}</div>
                            <div class="confidence">{texts['confidence']}: {confidence}%</div>
                        </div>
                    </div>
                    <div class="qd-pos-stats">
        '''

        if has_position:
            html += f'''
                        <div class="stat">
                            <div class="label">{texts['current_price']}</div>
                            <div class="value">${current_price:.4f}</div>
                        </div>
                        <div class="stat">
                            <div class="label">{texts['entry_price']}</div>
                            <div class="value">${entry_price:.4f}</div>
                        </div>
                        <div class="stat">
                            <div class="label">{texts['pnl']}</div>
                            <div class="value {pnl_class}">{pnl_sign}${pnl:.2f} ({pnl_sign}{pnl_pct:.1f}%)</div>
                        </div>
                        <div class="stat">
                            <div class="label">{texts['quantity']} / {texts['side']}</div>
                            <div class="value">{quantity} / {side_text}</div>
                        </div>
            '''
        else:
            html += f'''
                        <div class="stat">
                            <div class="label">{texts['latest_price']}</div>
                            <div class="value">${current_price:.4f}</div>
                        </div>
                        <div class="stat">
                            <div class="label">{texts['ai_decision']}</div>
                            <div class="value">{decision_text}</div>
                        </div>
                        <div class="stat">
                            <div class="label">{texts['confidence']}</div>
                            <div class="value">{confidence}%</div>
                        </div>
                        <div class="stat">
                            <div class="label">{texts['monitor_type']}</div>
                            <div class="value">{texts['watchlist']}</div>
                        </div>
            '''

        html += '''
                    </div>
        '''
        
        # Reasoning summary
        if reasoning:
            html += f'''
                    <div class="qd-pos-reasoning">
                        <div class="label">{texts['reasoning']}</div>
                        <div class="text qd-copy">{_format_report_prose(reasoning[:500] + ('...' if len(reasoning) > 500 else ''))}</div>
                    </div>
            '''
        
        # Generate unique ID for collapsible sections (use symbol hash to avoid special chars)
        section_id_base = hashlib.md5(
            f"{symbol}_{market}_{group_name}".encode(),
            usedforsecurity=False,
        ).hexdigest()[:8]
        
        # Collapsible: Trader Analysis
        if trader_reasoning:
            trader_id = f"trader_{section_id_base}"
            html += f'''
                    <div class="qd-collapsible">
                        <input type="checkbox" id="{trader_id}">
                        <label for="{trader_id}" class="qd-collapsible-header">
                            <span class="title">{texts['trader_report']}</span>
                            <span class="arrow">-&gt;</span>
                        </label>
                        <div class="qd-collapsible-content qd-copy">{_format_report_prose(trader_reasoning)}</div>
                    </div>
            '''
        
        # Collapsible: Market Overview
        if overview_report:
            overview_id = f"overview_{section_id_base}"
            html += f'''
                    <div class="qd-collapsible">
                        <input type="checkbox" id="{overview_id}">
                        <label for="{overview_id}" class="qd-collapsible-header">
                            <span class="title">{texts['overview_report']}</span>
                            <span class="arrow">-&gt;</span>
                        </label>
                        <div class="qd-collapsible-content qd-copy">{_format_report_prose(overview_report)}</div>
                    </div>
            '''
        
        # Collapsible: Risk Assessment
        if risk_report:
            risk_id = f"risk_{section_id_base}"
            html += f'''
                    <div class="qd-collapsible">
                        <input type="checkbox" id="{risk_id}">
                        <label for="{risk_id}" class="qd-collapsible-header">
                            <span class="title">{texts['risk_report']}</span>
                            <span class="arrow">-&gt;</span>
                        </label>
                        <div class="qd-collapsible-content qd-copy">{_format_report_list(risk_report)}</div>
                    </div>
            '''
        
        html += '''
                </div>
        '''
    
    # User focus section
    if custom_prompt:
        html += f'''
            </div>
            <div class="qd-section">
                <h2 class="qd-section-title">{texts['user_focus']}</h2>
                <div class="qd-user-focus">{custom_prompt}</div>
        '''
    
    # Footer
    html += f'''
            </div>
            <div class="qd-footer">
                <div class="time">{texts['generated_at']}: {time.strftime('%Y-%m-%d %H:%M:%S')}</div>
                <div class="disclaimer">{texts['disclaimer']}</div>
            </div>
        </div>
    </div>
    '''
    
    return html


def _build_telegram_report(
    positions: List[Dict[str, Any]],
    position_analyses: List[Dict[str, Any]],
    language: str,
    custom_prompt: str = ''
) -> str:
    """Build a concise Telegram-friendly report in HTML text."""
    labels = _outlook_labels(language)
    outlook_title = _monitor_report_texts(language)['ai_decision']

    def has_holding(pa: Dict[str, Any]) -> bool:
        return float(pa.get('quantity') or 0) > 0 and float(pa.get('entry_price') or 0) > 0

    held = [p for p in position_analyses if has_holding(p) and not p.get('error')]
    watched = [p for p in position_analyses if not has_holding(p) and not p.get('error')]
    errored = [p for p in position_analyses if p.get('error')]

    total_cost = sum(float(p.get('entry_price', 0)) * float(p.get('quantity', 0)) for p in held)
    total_pnl = sum(float(p.get('pnl', 0)) for p in held)
    total_pnl_pct = round(total_pnl / total_cost * 100, 2) if total_cost > 0 else 0
    pnl_sign = '+' if total_pnl >= 0 else ''

    buy_count = len([p for p in position_analyses if p.get('final_decision') == 'BUY'])
    sell_count = len([p for p in position_analyses if p.get('final_decision') == 'SELL'])
    hold_count = len([p for p in position_analyses if p.get('final_decision') == 'HOLD'])

    lines: List[str] = ["<b>AI Asset Analysis Report</b>", ""]
    overview = ["<b>Overview</b>"]
    if held:
        overview.append(f"Holdings: {len(held)}")
        overview.append(f"Total Cost: ${total_cost:,.2f}")
        overview.append(f"Total P&L: {pnl_sign}${total_pnl:,.2f} ({pnl_sign}{total_pnl_pct:.1f}%)")
    if watched:
        overview.append(f"Watchlist: {len(watched)}")
    lines.extend(overview)
    lines.extend(["", f"<b>{outlook_title}</b>", f"{labels['BUY']} {buy_count} | {labels['SELL']} {sell_count} | {labels['HOLD']} {hold_count}"])

    def render_analysis(pa: Dict[str, Any], show_pnl: bool) -> None:
        decision = str(pa.get('final_decision') or 'HOLD').upper()
        name = pa.get('name') or pa.get('symbol') or '-'
        lines.append(f"\n<b>{name}</b> ({pa.get('market')}/{pa.get('symbol')})")
        if show_pnl:
            pnl = float(pa.get('pnl') or 0)
            pnl_pct = float(pa.get('pnl_percent') or 0)
            sign = '+' if pnl >= 0 else ''
            lines.append(f"Current: ${float(pa.get('current_price') or 0):,.2f} | P&L: {sign}${pnl:,.2f} ({sign}{pnl_pct:.1f}%)")
        else:
            lines.append(f"Price: ${float(pa.get('current_price') or 0):,.2f}")
        lines.append(f"{outlook_title}: <b>{labels.get(decision, decision)}</b> (Conf: {pa.get('confidence', 50)}%)")
        reasoning = str(pa.get('reasoning') or '').strip()
        if reasoning:
            lines.append(reasoning[:150] + ('...' if len(reasoning) > 150 else ''))

    if held:
        lines.extend(["", "<b>Holdings</b>"])
        for analysis in held:
            render_analysis(analysis, show_pnl=True)
    if watched:
        lines.extend(["", "<b>Watchlist</b>"])
        for analysis in watched:
            render_analysis(analysis, show_pnl=False)
    for analysis in errored:
        label = analysis.get('name') or analysis.get('symbol') or '-'
        lines.append(f"\n<b>{label}</b>: Analysis failed")

    if custom_prompt:
        lines.extend(["", f"<b>Focus:</b> {custom_prompt}"])

    lines.extend(["", "----", f"<i>{time.strftime('%Y-%m-%d %H:%M')}</i>"])
    return '\n'.join(lines)


def _build_batch_telegram_report(
    monitor_results: List[Dict[str, Any]],
    language: str,
) -> str:
    """Build one Telegram report that combines multiple monitor results."""
    labels = _outlook_labels(language)
    outlook_title = _monitor_report_texts(language)['ai_decision']
    all_analyses: List[Dict[str, Any]] = []
    section_lines: List[str] = []

    for result in monitor_results:
        monitor = result.get('monitor') or {}
        name = monitor.get('name') or monitor.get('symbol') or 'Monitor'
        analyses = result.get('position_analyses') or []
        all_analyses.extend([a for a in analyses if isinstance(a, dict)])
        section_lines.append(f"\n<b>{name}</b>")
        if result.get('error'):
            section_lines.append(f"Failed: {result.get('error')}")
            continue
        for analysis in analyses:
            if analysis.get('error'):
                continue
            decision = str(analysis.get('final_decision') or 'HOLD').upper()
            label = analysis.get('name') or analysis.get('symbol') or '-'
            price = float(analysis.get('current_price') or 0)
            section_lines.append(f"{label}: {labels.get(decision, decision)}, ${price:,.2f}, conf {analysis.get('confidence', 50)}%")

    buy_count = len([p for p in all_analyses if p.get('final_decision') == 'BUY'])
    sell_count = len([p for p in all_analyses if p.get('final_decision') == 'SELL'])
    hold_count = len([p for p in all_analyses if p.get('final_decision') == 'HOLD'])

    header = [
        "<b>Scheduled Portfolio Report</b>",
        "",
        f"Monitors: {len(monitor_results)}",
        f"Symbols: {len(all_analyses)}",
        f"{outlook_title}: {labels['BUY']} {buy_count} | {labels['SELL']} {sell_count} | {labels['HOLD']} {hold_count}",
    ]
    header.extend(section_lines)
    header.extend(["", "----", f"<i>{time.strftime('%Y-%m-%d %H:%M')}</i>"])
    return '\n'.join(header)
def _build_batch_html_report(
    monitor_results: List[Dict[str, Any]],
    language: str,
) -> str:
    """Build a combined HTML report for browser / email channel."""
    parts: List[str] = []
    for res in monitor_results:
        report = res.get('analysis', '')
        if report:
            parts.append(report)
    if not parts:
        return ''
    if len(parts) == 1:
        return parts[0]
    divider = '<hr style="border:none;border-top:1px solid #e8e8e8;margin:24px 0;">'
    return divider.join(parts)


def _send_batch_notification(
    user_id: int,
    monitor_results: List[Dict[str, Any]],
) -> None:
    """Send a single combined notification for multiple monitor results belonging to one user."""
    if not monitor_results:
        return

    successful = [r for r in monitor_results if r.get('success')]
    if not successful:
        for r in monitor_results:
            meta = r.get('_meta', {})
            _send_monitor_notification(
                monitor_name=meta.get('monitor_name', '?'),
                result=r,
                notification_config=meta.get('notification_config', {}),
                positions=meta.get('positions', []),
                position_analyses=meta.get('position_analyses', []),
                language=meta.get('language', 'en-US'),
                custom_prompt=meta.get('custom_prompt', ''),
                user_id=user_id,
            )
        return

    first_meta = successful[0].get('_meta', {})
    language = first_meta.get('language', 'en-US')

    # Merge channels from all monitors (union)
    all_channels: set = set()
    for r in successful:
        m = r.get('_meta', {})
        nc = m.get('notification_config', {})
        chs = nc.get('channels')
        if isinstance(chs, str):
            chs = [chs]
        elif not isinstance(chs, list):
            chs = []
        for c in chs:
            if c:
                all_channels.add(str(c).strip().lower())
    if not all_channels:
        all_channels = {'browser'}

    merged_nc = {'channels': list(all_channels), 'targets': {}}
    resolved_nc = resolve_notification_delivery(user_id, merged_nc)
    channels = resolved_nc.get('channels') or ['browser']
    targets = resolved_nc.get('targets', {})

    is_zh = language.startswith('zh')
    names = ', '.join(r.get('_meta', {}).get('monitor_name', '?') for r in successful)
    title = f"Scheduled Report: {names}"
    if len(title) > 255:
        title = title[:252] + '...'

    html_report = _build_batch_html_report(successful, language)
    telegram_report = _build_batch_telegram_report(successful, language)

    try:
        notifier = SignalNotifier()
        for channel in channels:
            try:
                ch = str(channel).strip().lower()
                if ch == 'browser':
                    with get_db_connection() as db:
                        cur = db.cursor()
                        cur.execute(
                            """
                            INSERT INTO qd_strategy_notifications
                            (user_id, strategy_id, symbol, signal_type, channels, title, message, payload_json, created_at)
                            VALUES (?, NULL, ?, ?, ?, ?, ?, ?, NOW())
                            """,
                            (user_id, 'PORTFOLIO', 'ai_monitor', 'browser', title, html_report,
                             json.dumps({'batch': True, 'count': len(successful)}, ensure_ascii=False, default=str)),
                        )
                        db.commit()
                        cur.close()
                elif ch == 'telegram':
                    chat_id = targets.get('telegram', '')
                    token_override = targets.get('telegram_bot_token', '')
                    if chat_id:
                        notifier._notify_telegram(
                            chat_id=chat_id, text=telegram_report,
                            token_override=token_override, parse_mode="HTML",
                        )
                elif ch == 'email':
                    to_email = targets.get('email', '')
                    if to_email:
                        notifier._notify_email(
                            to_email=to_email, subject=title,
                            body_text=html_report, body_html=html_report,
                        )
                elif ch == 'webhook':
                    url = targets.get('webhook', '')
                    if url:
                        notifier._notify_webhook(
                            url=url,
                            payload={
                                'type': 'portfolio_monitor_batch',
                                'monitors': [r.get('_meta', {}).get('monitor_name') for r in successful],
                                'html_report': html_report,
                            },
                            token_override=targets.get('webhook_token') or None,
                            signing_secret_override=targets.get('webhook_signing_secret') or None,
                        )
            except Exception as e:
                logger.warning(f"Batch notification channel {channel} failed: {e}")
    except Exception as e:
        logger.error(f"_send_batch_notification failed: {e}")


def _send_monitor_notification(
    monitor_name: str,
    result: Dict[str, Any],
    notification_config: Dict[str, Any],
    positions: List[Dict[str, Any]] = None,
    position_analyses: List[Dict[str, Any]] = None,
    language: str = 'en-US',
    custom_prompt: str = '',
    user_id: int = None
) -> None:
    """Send notification with analysis result using appropriate format for each channel."""
    try:
        notifier = SignalNotifier()
        effective_user_id = user_id if user_id is not None else DEFAULT_USER_ID
        notification_config = resolve_notification_delivery(effective_user_id, notification_config)

        channels = notification_config.get('channels') or ['browser']
        targets = notification_config.get('targets', {})

        title = f"Portfolio Monitor: {monitor_name}"
        if len(title) > 255:
            title = title[:252] + '...'
        
        if not result.get('success'):
            error_title = f"Monitor Failed: {monitor_name}"
            if len(error_title) > 255:
                error_title = error_title[:252] + '...'
            error_msg = f"Analysis failed: {result.get('error', 'Unknown error')}"
            
            for channel in channels:
                try:
                    ch = str(channel).strip().lower()
                    if ch == 'browser':
                        with get_db_connection() as db:
                            cur = db.cursor()
                            cur.execute(
                                """
                                INSERT INTO qd_strategy_notifications
                                (user_id, strategy_id, symbol, signal_type, channels, title, message, payload_json, created_at)
                                VALUES (?, NULL, ?, ?, ?, ?, ?, ?, NOW())
                                """,
                                (effective_user_id, 'PORTFOLIO', 'ai_monitor', 'browser', error_title, error_msg,
                                 json.dumps(result, ensure_ascii=False, default=str))
                            )
                            db.commit()
                            cur.close()
                    elif ch == 'telegram':
                        chat_id = targets.get('telegram', '')
                        token_override = targets.get('telegram_bot_token', '')
                        if chat_id:
                            notifier._notify_telegram(chat_id=chat_id, text=f"<b>{error_title}</b>\n\n{error_msg}", token_override=token_override, parse_mode="HTML")
                    elif ch == 'email':
                        to_email = targets.get('email', '')
                        if to_email:
                            notifier._notify_email(to_email=to_email, subject=error_title, body_text=error_msg)
                    elif ch == 'webhook':
                        url = targets.get('webhook', '')
                        if url:
                            notifier._notify_webhook(
                                url=url,
                                payload={
                                    'type': 'portfolio_monitor_error',
                                    'monitor_name': monitor_name,
                                    'title': error_title,
                                    'message': error_msg,
                                    'result': result,
                                },
                                token_override=targets.get('webhook_token') or None,
                                signing_secret_override=targets.get('webhook_signing_secret') or None,
                            )
                except Exception as e:
                    logger.warning(f"Failed to send error notification to {channel}: {e}")
            return
        
        # Generate reports for different channels
        html_report = result.get('analysis', '')  # This is already HTML from _build_html_report
        
        # Generate Telegram-specific report if we have the data
        telegram_report = ''
        if positions is not None and position_analyses is not None:
            telegram_report = _build_telegram_report(positions, position_analyses, language, custom_prompt)
        else:
            # Fallback: strip HTML tags for Telegram
            import re
            telegram_report = re.sub(r'<[^>]+>', '', html_report)
            if len(telegram_report) > 4000:
                telegram_report = telegram_report[:4000] + '...'
        
        # Send to each channel
        for channel in channels:
            try:
                ch = str(channel).strip().lower()
                
                if ch == 'browser':
                    # Browser notification uses HTML report
                    with get_db_connection() as db:
                        cur = db.cursor()
                        cur.execute(
                            """
                            INSERT INTO qd_strategy_notifications
                            (user_id, strategy_id, symbol, signal_type, channels, title, message, payload_json, created_at)
                            VALUES (?, NULL, ?, ?, ?, ?, ?, ?, NOW())
                            """,
                            (effective_user_id, 'PORTFOLIO', 'ai_monitor', 'browser', title, html_report,
                             json.dumps(result, ensure_ascii=False, default=str))
                        )
                        db.commit()
                        cur.close()
                
                elif ch == 'telegram':
                    chat_id = targets.get('telegram', '')
                    token_override = targets.get('telegram_bot_token', '')
                    if chat_id:
                        # Use Telegram-optimized format
                        notifier._notify_telegram(
                            chat_id=chat_id,
                            text=telegram_report,
                            token_override=token_override,
                            parse_mode="HTML"
                        )
                
                elif ch == 'email':
                    to_email = targets.get('email', '')
                    if to_email:
                        # Email uses full HTML report
                        notifier._notify_email(
                            to_email=to_email,
                            subject=title,
                            body_text=html_report,
                            body_html=html_report  # Send as HTML email
                        )
                
                elif ch == 'webhook':
                    url = targets.get('webhook', '')
                    if url:
                        notifier._notify_webhook(
                            url=url,
                            payload={
                                'type': 'portfolio_monitor',
                                'monitor_name': monitor_name,
                                'result': result,
                                'html_report': html_report
                            },
                            token_override=targets.get('webhook_token') or None,
                            signing_secret_override=targets.get('webhook_signing_secret') or None,
                        )
                        
            except Exception as e:
                logger.warning(f"Failed to send notification to {channel}: {e}")
                
    except Exception as e:
        logger.error(f"_send_monitor_notification failed: {e}")


def run_single_monitor(
    monitor_id: int,
    override_language: str = None,
    user_id: int = None,
    skip_notification: bool = False,
) -> Dict[str, Any]:
    """Run a single monitor and return the result.

    Args:
        monitor_id: The monitor ID to run
        override_language: Optional language override (e.g., 'zh-CN', 'en-US')
        user_id: Optional user ID for user isolation
        skip_notification: If True, do NOT send a notification (caller will batch-send later)
    """
    try:
        effective_user_id = user_id if user_id is not None else DEFAULT_USER_ID

        with get_db_connection() as db:
            cur = db.cursor()
            cur.execute(
                """
                SELECT id, user_id, name, position_ids, monitor_type, config, notification_config
                FROM qd_position_monitors
                WHERE id = ? AND user_id = ?
                """,
                (monitor_id, effective_user_id)
            )
            row = cur.fetchone()
            cur.close()

        if not row:
            return {'success': False, 'error': 'Monitor not found'}

        monitor_user_id = int(row.get('user_id') or effective_user_id)
        name = row.get('name') or f'Monitor #{monitor_id}'
        position_ids = safe_json_loads(row.get('position_ids'), [])
        monitor_type = row.get('monitor_type') or 'ai'
        config = safe_json_loads(row.get('config'), {})
        notification_config = safe_json_loads(row.get('notification_config'), {})

        if override_language:
            config['language'] = override_language

        interval_minutes = int(
            config.get('run_interval_minutes')
            or config.get('interval_minutes')
            or 60
        )

        if position_ids:
            positions = _get_positions_for_monitor(position_ids, user_id=monitor_user_id)
        elif config.get('symbol'):
            target_sym = config['symbol'].strip().upper()
            target_mkt = (config.get('market') or '').strip()

            # Rule 4: symbol deleted from watchlist, skip.
            still_in_watchlist = False
            try:
                with get_db_connection() as db:
                    cur = db.cursor()
                    wl_sql = "SELECT 1 FROM qd_watchlist WHERE user_id = ? AND UPPER(symbol) = ?"
                    wl_args: list = [monitor_user_id, target_sym]
                    if target_mkt:
                        wl_sql += " AND market = ?"
                        wl_args.append(target_mkt)
                    wl_sql += " LIMIT 1"
                    cur.execute(wl_sql, tuple(wl_args))
                    still_in_watchlist = cur.fetchone() is not None
                    cur.close()
            except Exception as e:
                logger.warning(f"Monitor #{monitor_id} watchlist check failed: {e}")

            if not still_in_watchlist:
                logger.info(f"Monitor #{monitor_id} skipped: {target_mkt}:{target_sym} removed from watchlist")
                skip_result = {
                    'success': False,
                    'error': 'Symbol removed from watchlist',
                    'skipped': True,
                    'timestamp': _now_ts(),
                }
                _bump_monitor_schedule(monitor_id, interval_minutes, skip_result, skipped=True)
                return skip_result

            # Rules 1&2: match real position if exists, otherwise virtual observation
            matched = _get_positions_for_monitor(None, user_id=monitor_user_id)
            positions = [
                p for p in matched
                if (p.get('symbol') or '').strip().upper() == target_sym
                and (not target_mkt or (p.get('market') or '').strip() == target_mkt)
            ]
            if not positions:
                positions = [{
                    'market': target_mkt,
                    'symbol': config['symbol'].strip(),
                    'name': config.get('name', config['symbol']).strip(),
                    'side': 'long',
                    'quantity': 0,
                    'entry_price': 0,
                    'current_price': 0,
                    'pnl': 0,
                    'pnl_percent': 0,
                }]
        else:
            # Rule 5: no position_ids and no config.symbol; nothing to analyze.
            positions = []

        if not positions:
            logger.info(f"Monitor #{monitor_id} skipped: no matching positions found")
            skip_result = {
                'success': False,
                'error': 'No matching positions found',
                'skipped': True,
                'timestamp': _now_ts(),
            }
            _bump_monitor_schedule(monitor_id, interval_minutes, skip_result, skipped=True)
            return skip_result

        # Billing check before running monitor analysis.
        billing = get_billing_service()
        symbol_count = len(positions)
        per_symbol_cost = billing.get_feature_cost('ai_analysis')
        total_cost = per_symbol_cost * symbol_count

        if total_cost > 0 and billing.is_billing_enabled():
            user_credits = billing.get_user_credits(monitor_user_id)
            if user_credits < total_cost:
                logger.warning(
                    f"Monitor #{monitor_id} skipped: insufficient credits "
                    f"({user_credits} < {total_cost} for {symbol_count} symbols)"
                )
                skip_result = {
                    'success': False,
                    'error': f'Insufficient credits: need {total_cost}, have {user_credits}',
                    'skipped': True,
                    'timestamp': _now_ts(),
                }
                _bump_monitor_schedule(monitor_id, interval_minutes, skip_result, skipped=True)
                return skip_result
            for i in range(symbol_count):
                pos = positions[i]
                ok, msg = billing.check_and_consume(
                    user_id=monitor_user_id,
                    feature='ai_analysis',
                    reference_id=f"monitor_{monitor_id}_{pos.get('symbol', '')}"
                )
                if not ok:
                    logger.warning(f"Monitor #{monitor_id} billing failed at symbol #{i+1}: {msg}")
                    break

        if monitor_type == 'ai':
            result = _run_ai_analysis(positions, config, user_id=monitor_user_id)
        else:
            result = {'success': False, 'error': f'Unsupported monitor type: {monitor_type}'}

        # Advance the schedule using PostgreSQL's NOW() / INTERVAL to stay
        # consistent with the INSERT path (routes/portfolio.py) and avoid any
        # naive vs aware timestamp drift on the TIMESTAMP columns.
        _bump_monitor_schedule(monitor_id, interval_minutes, result, skipped=False)

        language = config.get('language', 'en-US')
        custom_prompt = config.get('prompt', '')
        position_analyses = result.get('position_analyses', [])
        deduped_positions = result.get('positions', positions)

        # Attach metadata used by batch notification / history
        result['_meta'] = {
            'monitor_id': monitor_id,
            'monitor_name': name,
            'user_id': monitor_user_id,
            'language': language,
            'custom_prompt': custom_prompt,
            'notification_config': notification_config,
            'positions': deduped_positions,
            'position_analyses': position_analyses,
        }

        if not skip_notification:
            _send_monitor_notification(
                monitor_name=name,
                result=result,
                notification_config=notification_config,
                positions=deduped_positions,
                position_analyses=position_analyses,
                language=language,
                custom_prompt=custom_prompt,
                user_id=monitor_user_id,
            )

        return result
    except Exception as e:
        logger.error(f"run_single_monitor failed: {e}")
        logger.error(traceback.format_exc())
        return {'success': False, 'error': str(e)}


def _check_position_alerts():
    """Check all active alerts and trigger notifications if conditions are met."""
    from datetime import datetime, timezone
    try:
        kline_service = KlineService()
        notifier = SignalNotifier()
        now = datetime.now(timezone.utc)
        price_cache: Dict[str, float] = {}
        
        with get_db_connection() as db:
            cur = db.cursor()
            # Get active alerts for all users that haven't been triggered (or can repeat)
            cur.execute(
                """
                SELECT a.id, a.user_id, a.position_id, a.market, a.symbol, a.alert_type, a.threshold,
                       a.notification_config, a.is_triggered, a.last_triggered_at, a.repeat_interval,
                       p.entry_price, p.quantity, p.side, p.name as position_name
                FROM qd_position_alerts a
                LEFT JOIN qd_manual_positions p ON a.position_id = p.id
                WHERE a.is_active = 1
                ORDER BY a.updated_at ASC, a.id ASC
                LIMIT ?
                """
                ,
                (MAX_ALERTS_PER_MONITOR_TICK,),
            )
            alerts = cur.fetchall() or []
            cur.close()
        if len(alerts) >= MAX_ALERTS_PER_MONITOR_TICK:
            logger.warning(
                "Position alert check reached per-tick limit=%s; remaining alerts will be checked in later ticks",
                MAX_ALERTS_PER_MONITOR_TICK,
            )
        
        for alert in alerts:
            try:
                alert_id = alert.get('id')
                alert_user_id = int(alert.get('user_id') or 1)
                alert_type = alert.get('alert_type')
                threshold = float(alert.get('threshold') or 0)
                market = alert.get('market')
                symbol = alert.get('symbol')
                is_triggered = bool(alert.get('is_triggered'))
                last_triggered_at = alert.get('last_triggered_at')  # datetime or None
                repeat_interval = int(alert.get('repeat_interval') or 0)
                notification_config = safe_json_loads(alert.get('notification_config'), {})
                
                # Check if we can trigger (not triggered yet, or repeat interval passed)
                can_trigger = not is_triggered
                if is_triggered and repeat_interval > 0 and last_triggered_at:
                    # Convert last_triggered_at to timezone-aware if needed
                    if last_triggered_at.tzinfo is None:
                        last_triggered_at = last_triggered_at.replace(tzinfo=timezone.utc)
                    elapsed_seconds = (now - last_triggered_at).total_seconds()
                    if elapsed_seconds >= repeat_interval:
                        can_trigger = True
                
                if not can_trigger:
                    continue
                
                # Get current price (use realtime price API)
                current_price = 0
                try:
                    price_key = f"{str(market or '').strip().lower()}:{str(symbol or '').strip().upper()}"
                    if price_key in price_cache:
                        current_price = price_cache[price_key]
                    else:
                        price_data = kline_service.get_realtime_price(market, symbol)
                        current_price = float(price_data.get('price') or 0)
                        price_cache[price_key] = current_price
                except Exception:
                    price_cache[price_key] = 0
                    continue
                
                if current_price <= 0:
                    continue
                
                triggered = False
                alert_message = ""
                
                # Get language from notification_config (saved when alert was created)
                alert_language = notification_config.get('language', 'en-US')
                
                if alert_type == 'price_above':
                    if current_price >= threshold:
                        triggered = True
                        alert_message = get_alert_message(
                            'price_above', alert_language,
                            symbol=symbol, current_price=current_price, threshold=threshold
                        )
                
                elif alert_type == 'price_below':
                    if current_price <= threshold:
                        triggered = True
                        alert_message = get_alert_message(
                            'price_below', alert_language,
                            symbol=symbol, current_price=current_price, threshold=threshold
                        )
                
                elif alert_type in ('pnl_above', 'pnl_below'):
                    entry_price = float(alert.get('entry_price') or 0)
                    quantity = float(alert.get('quantity') or 0)
                    side = alert.get('side') or 'long'
                    
                    if entry_price > 0 and quantity > 0:
                        if side == 'long':
                            pnl = (current_price - entry_price) * quantity
                        else:
                            pnl = (entry_price - current_price) * quantity
                        pnl_percent = pnl / (entry_price * quantity) * 100
                        
                        if alert_type == 'pnl_above' and pnl_percent >= threshold:
                            triggered = True
                            alert_message = get_alert_message(
                                'pnl_above', alert_language,
                                symbol=symbol, pnl_percent=pnl_percent, threshold=threshold
                            )
                        elif alert_type == 'pnl_below' and pnl_percent <= threshold:
                            triggered = True
                            alert_message = get_alert_message(
                                'pnl_below', alert_language,
                                symbol=symbol, pnl_percent=pnl_percent, threshold=threshold
                            )
                
                if triggered:
                    logger.info(f"Alert #{alert_id} triggered: {alert_message}")
                    
                    # Update alert status
                    with get_db_connection() as db:
                        cur = db.cursor()
                        cur.execute(
                            """
                            UPDATE qd_position_alerts
                            SET is_triggered = 1, last_triggered_at = NOW(), trigger_count = trigger_count + 1, updated_at = NOW()
                            WHERE id = ?
                            """,
                            (alert_id,)
                        )
                        db.commit()
                        cur.close()
                    
                    resolved = resolve_notification_delivery(alert_user_id, notification_config)
                    channels = resolved.get('channels') or ['browser']
                    targets = resolved.get('targets', {})
                    alert_title = get_alert_title(alert_language)
                    
                    for channel in channels:
                        try:
                            ch = str(channel).strip().lower()
                            if ch == 'browser':
                                with get_db_connection() as db:
                                    cur = db.cursor()
                                    cur.execute(
                                        """
                                        INSERT INTO qd_strategy_notifications
                                        (user_id, strategy_id, symbol, signal_type, channels, title, message, payload_json, created_at)
                                        VALUES (?, NULL, ?, ?, ?, ?, ?, ?, NOW())
                                        """,
                                        (alert_user_id, symbol, 'price_alert', 'browser', alert_title, alert_message,
                                         json.dumps({'alert_id': alert_id, 'alert_type': alert_type}, ensure_ascii=False))
                                    )
                                    db.commit()
                                    cur.close()
                            elif ch == 'telegram':
                                chat_id = targets.get('telegram', '')
                                token_override = targets.get('telegram_bot_token', '')
                                if chat_id:
                                    notifier._notify_telegram(chat_id=chat_id, text=alert_message, token_override=token_override, parse_mode="HTML")
                            elif ch == 'email':
                                to_email = targets.get('email', '')
                                if to_email:
                                    notifier._notify_email(to_email=to_email, subject=alert_title, body_text=alert_message)
                        except Exception as e:
                            logger.warning(f"Failed to send alert notification: {e}")
                            
            except Exception as e:
                logger.warning(f"Error processing alert: {e}")
                
    except Exception as e:
        logger.error(f"_check_position_alerts failed: {e}")


def notify_strategy_signal_for_positions(market: str, symbol: str, signal_type: str, signal_detail: str, user_id: int = None):
    """
    Called when a strategy signal is triggered.
    Check if the **strategy owner** has manual positions in this symbol and send a
    notification to them.

    Security note: this function is fail-closed on ``user_id``. Earlier versions
    silently fell back to ``WHERE symbol = ?`` (no user filter) when callers
    omitted ``user_id``, which caused user A's strategy signal to fan out to
    every user holding the same symbol and leaked strategy name / signal
    details across tenants. Callers MUST pass the strategy owner's ``user_id``.
    """
    try:
        symbol = (symbol or '').strip().upper()
        if not symbol:
            return

        if user_id is None:
            logger.warning(
                "notify_strategy_signal_for_positions called without user_id; "
                "refusing to broadcast across users (symbol=%s, signal=%s)",
                symbol, signal_type,
            )
            return

        with get_db_connection() as db:
            cur = db.cursor()
            cur.execute(
                """
                SELECT id, user_id, market, symbol, name, side, quantity, entry_price, group_name
                FROM qd_manual_positions
                WHERE user_id = ? AND symbol = ?
                """,
                (user_id, symbol),
            )
            positions = cur.fetchall() or []
            cur.close()
        
        if not positions:
            return
        
        # User has positions in this symbol - send notification
        notifier = SignalNotifier()
        now = _now_ts()
        
        for pos in positions:
            pos_user_id = int(pos.get('user_id') or 1)
            pos_name = pos.get('name') or symbol
            pos_side = pos.get('side') or 'long'
            quantity = float(pos.get('quantity') or 0)
            entry_price = float(pos.get('entry_price') or 0)
            
            title = f"Strategy Signal: {pos_name}"
            message = (
                f"Strategy signal: {signal_type}\n\n"
                f"Symbol: {market}/{symbol}\n"
                f"Position: {pos_side.upper()} {quantity} @ {entry_price:.4f}\n\n"
                f"Signal detail:\n{signal_detail}\n\n"
                "This notification is generated from a strategy signal linked to the position."
            )
            
            # Save browser notification
            with get_db_connection() as db:
                cur = db.cursor()
                cur.execute(
                    """
                    INSERT INTO qd_strategy_notifications
                    (user_id, strategy_id, symbol, signal_type, channels, title, message, payload_json, created_at)
                    VALUES (?, NULL, ?, ?, ?, ?, ?, ?, NOW())
                    """,
                    (pos_user_id, symbol, 'strategy_linkage', 'browser', title, message,
                     json.dumps({'signal_type': signal_type}, ensure_ascii=False))
                )
                db.commit()
                cur.close()
        
        logger.info(f"Strategy signal linkage: notified {len(positions)} position(s) for {symbol}")
        
    except Exception as e:
        logger.error(f"notify_strategy_signal_for_positions failed: {e}")


def _monitor_loop():
    """Background loop that checks and runs due monitors.

    All monitors due in the same cycle are executed first (with skip_notification),
    then results are grouped by user_id and sent as one combined notification per user.
    """
    logger.info("Portfolio monitor background loop started")

    while not _stop_event.is_set():
        try:
            if is_fd_cooldown_active():
                logger.warning(
                    "Portfolio monitor tick skipped: FD cooldown active for %.0fs",
                    fd_cooldown_remaining(),
                )
                _stop_event.wait(min(30, max(1, int(fd_cooldown_remaining()))))
                continue

            _check_position_alerts()

            with get_db_connection() as db:
                cur = db.cursor()
                batch_limit = _due_monitor_batch_limit()
                cur.execute(
                    """
                    SELECT id, user_id FROM qd_position_monitors
                    WHERE is_active = 1 AND next_run_at <= NOW()
                    ORDER BY next_run_at ASC
                    LIMIT ?
                    """,
                    (batch_limit,),
                )
                rows = cur.fetchall() or []
                cur.close()

            # Collect results per user
            user_results: Dict[int, List[Dict[str, Any]]] = {}
            for row in rows:
                if _stop_event.is_set():
                    break
                monitor_id = row.get('id')
                monitor_user_id = int(row.get('user_id') or 1)
                if not monitor_id:
                    continue
                logger.info(f"Running due monitor #{monitor_id} for user #{monitor_user_id}")
                try:
                    result = run_single_monitor(
                        monitor_id,
                        user_id=monitor_user_id,
                        skip_notification=True,
                    )
                    user_results.setdefault(monitor_user_id, []).append(result)
                except Exception as e:
                    logger.error(f"Monitor #{monitor_id} execution failed: {e}")

            # Send one combined notification per user
            for uid, results in user_results.items():
                try:
                    if len(results) == 1:
                        meta = results[0].get('_meta', {})
                        _send_monitor_notification(
                            monitor_name=meta.get('monitor_name', '?'),
                            result=results[0],
                            notification_config=meta.get('notification_config', {}),
                            positions=meta.get('positions', []),
                            position_analyses=meta.get('position_analyses', []),
                            language=meta.get('language', 'en-US'),
                            custom_prompt=meta.get('custom_prompt', ''),
                            user_id=uid,
                        )
                    else:
                        _send_batch_notification(uid, results)
                except Exception as e:
                    logger.error(f"Batch notification for user #{uid} failed: {e}")

        except Exception as e:
            logger.error(f"Monitor loop error: {e}")

        _stop_event.wait(30)

    logger.info("Portfolio monitor background loop stopped")


def start_monitor_service():
    """Start the background monitor service."""
    global _monitor_thread
    
    if _monitor_thread and _monitor_thread.is_alive():
        logger.info("Portfolio monitor service already running")
        return
    
    _stop_event.clear()
    _monitor_thread = threading.Thread(target=_monitor_loop, daemon=True, name="PortfolioMonitor")
    _monitor_thread.start()
    logger.info("Portfolio monitor service started")


def stop_monitor_service():
    """Stop the background monitor service."""
    global _monitor_thread
    
    _stop_event.set()
    if _monitor_thread:
        _monitor_thread.join(timeout=5)
        _monitor_thread = None
    logger.info("Portfolio monitor service stopped")
